### PR TITLE
Updated and split entities to use client methods

### PR DESCRIPTION
**Pull request by QuantumToasted**
This PR....actually does what I wanted it to. It also switches the order of the parameters on BanMemberAsync (and all methods which call it), swapping the amount of days of messages to delete with the reason, to reduce redundant method overloads. Capiche?

### CODE REVIEW

**Comment by Quahu** [comment]
I'm debating whether we should completely remove CreateRelationshipAsync() with the nullable type 
from both the entities and the client and replace it with BlockUserAsync() and another method (SendFriendRequestAsync()?) for adding someone as a friend.

**Comment by QuantumToasted** [comment]
It's up to you, I think if we're going to split the methods explicitly for blocking and adding friends, then there should be one for accepting friend requests as well, so as to not leave any of the possibilities of CreateRelationshipAsync() being missed out. Whatever the actual arguments would be to do that, at least.

**Comment by Quahu** [comment]
The API call to accept a friend request is the exact same as for adding someone as a friend.

**Comment by QuantumToasted** [comment]
Ah, yes, consistency. I think splitting them is a good idea b/c then people won't make the same mistake I was trying to make while writing this, being confused by incoming and outgoing friend requests.

**Comment by Quahu** [comment]
Perhaps we should leave SendFriendRequestAsync() on the client for the Discord tags, and call the method one the user, that'd both send friend requests and accept them, AddFriendAsync() or something. Maybe that'd be a better name for this behavior.

**Pull request merged**
