### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by quinchs**
Adds a better nav bar link for the github

## Description

Adds the yes

Fixes #69420

## Checklist

- [ ] fartdoodoofart

### CODE REVIEW

**Review by Neuheit — COMMENTED** [review]
Did you properly test this PR?

**Comment by quinchs** [comment]
Yes i can confirm it does the yes

**Comment by AnotherZane** [comment]
LGTM!

**Comment by Zackattak01** [comment]
:+1:  :rocket:

**Pull request closed without merging**
